// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIY152qe_hUfgPiEyiYERvmo3UT_G8wu0',
    appId: '1:722998649522:web:eedeff9fbc2ea1e1965fab',
    messagingSenderId: '722998649522',
    projectId: 'ksebl-smartbilling',
    authDomain: 'ksebl-smartbilling.firebaseapp.com',
    storageBucket: 'ksebl-smartbilling.firebasestorage.app',
    measurementId: 'G-KH50YWMMQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlmjDTa59lICL8sZVjUN8D-1IDDqq1eOA',
    appId: '1:722998649522:android:6616df0e2dda604b965fab',
    messagingSenderId: '722998649522',
    projectId: 'ksebl-smartbilling',
    storageBucket: 'ksebl-smartbilling.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhO-5eucrdpV4FKdgoaNELnqUy-FoLWt4',
    appId: '1:722998649522:ios:2e2a9205bfa37c1e965fab',
    messagingSenderId: '722998649522',
    projectId: 'ksebl-smartbilling',
    storageBucket: 'ksebl-smartbilling.firebasestorage.app',
    iosBundleId: 'com.example.smartBilling',
  );
}
