analyzer:
  errors:
    avoid_print: ignore
    deprecated_member_use: ignore
    prefer_typing_uninitialized_variables: ignore
    use_build_context_synchronously: ignore
include: package:flutter_lints/flutter.yaml
