name: smart_billing
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.5.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  fluttertoast: ^8.2.12
  html: ^0.15.5
  http: ^1.3.0
  #flutter_launcher_icons: ^0.14.3
  #icons_launcher: ^2.0.7
  #icons_launcher: ^2.0.7
  image_picker: ^1.1.2
  intl: ^0.20.2
  open_file: ^3.5.10
  path_provider: ^2.1.5
  razorpay_flutter: ^1.4.0
  shared_preferences: ^2.3.3
  syncfusion_flutter_pdf: ^28.2.11
  tflite_flutter: ^0.11.0
  tflite_flutter_helper_plus: ^0.0.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter  
  icons_launcher: ^2.0.7

icons_launcher:
  image_path: "assets/app_icon.png"  # Path to your icon
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/model.tflite
    - assets/labels.txt
